# Generated by Django 3.1.7 on 2021-04-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myblogpost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=30)),
                ('blog_description', models.TextField()),
                ('blog_by', models.CharField(max_length=30)),
                ('blog_sub_title', models.CharField(max_length=30)),
                ('pub_data', models.DateTimeField()),
                ('blog_img', models.ImageField(default='', upload_to='blogpics/images')),
                ('blog_category', models.CharField(max_length=40)),
            ],
        ),
    ]
