# Generated by Django 3.1.4 on 2021-04-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogpost',
            name='slug',
            field=models.CharField(default=0, max_length=130),
            preserve_default=False,
        ),
    ]
