# Generated by Django 3.1.4 on 2021-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210424_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
