# Generated by Django 3.1.4 on 2021-04-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='postviews',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
