# Generated by Django 3.1.4 on 2021-04-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postviews_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblogpost',
            name='slug',
        ),
    ]
