# Generated by Django 3.1.7 on 2021-04-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=50)),
                ('news_description', models.CharField(max_length=2000)),
                ('news_image', models.ImageField(default='', upload_to='newspics/images')),
                ('news_category', models.CharField(max_length=50)),
                ('news_date', models.DateTimeField()),
                ('news_by', models.CharField(max_length=50)),
            ],
        ),
    ]
