# Generated by Django 3.1.7 on 2021-04-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
                ('c_email', models.EmailField(max_length=50)),
                ('c_phone', models.CharField(max_length=20)),
                ('c_message', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='news_description',
            field=models.TextField(),
        ),
    ]
