# Generated by Django 3.1.4 on 2021-04-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20210416_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sub_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
