# Generated by Django 3.1.4 on 2021-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_subject_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_notes',
            field=models.FileField(default='', upload_to='notes/'),
        ),
    ]
