# Generated by Django 3.1.4 on 2021-04-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20210419_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
