# Generated by Django 3.1.4 on 2021-04-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20210428_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='reference_books',
            field=models.FileField(default='', null=True, upload_to='referencebooks/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_practicals_list',
            field=models.FileField(default='', null=True, upload_to='practicals/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_previous_year_paper',
            field=models.FileField(default='', null=True, upload_to='pyq/'),
        ),
    ]
