# Generated by Django 3.1.4 on 2021-04-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_auto_20210429_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='reference_books',
            field=models.FileField(blank=True, default='', upload_to='referencebooks/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_practicals_list',
            field=models.FileField(blank=True, default='', upload_to='practicals/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_previous_year_paper',
            field=models.FileField(blank=True, default='', upload_to='pyq/'),
        ),
    ]
