# Generated by Django 3.1.4 on 2021-04-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_auto_20210429_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_practicals',
            field=models.FileField(blank=True, default='', upload_to='practicals/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subjet_syllabus',
            field=models.FileField(default='', upload_to='syllabus/'),
        ),
    ]
