# Generated by Django 3.1.4 on 2021-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_auto_20210429_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='reference_links',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
